//! build.rs — code-generator for NLP keyword constants.
//!
//! Reads `config/nlp_keywords.toml` (one level above the crate root) and
//! emits `$OUT_DIR/keywords.rs` containing three static slices:
//!
//!   IMPACT_KEYWORD_DATA : &[(&str, &[&str])]
//!   NEED_KEYWORD_DATA   : &[(&str, &[&str])]
//!   RISK_KEYWORD_DATA   : &[&str]
//!
//! These are `include!`-ed by `src/text_classify.rs` at compile time, so the
//! keyword tables have a single source of truth (the TOML file) shared with
//! the Python runtime (which reads the same file via `tomllib`).
//!
//! Cargo will re-run this script automatically when the TOML file changes.

use std::{fs, path::Path};

fn main() {
    // CARGO_MANIFEST_DIR is the crate root (rust_core/); parent is workspace root.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR not set");
    let workspace_root = Path::new(&manifest_dir)
        .parent()
        .expect("build.rs: manifest dir has no parent");
    let toml_path = workspace_root.join("config").join("nlp_keywords.toml");

    // Tell Cargo to re-run this build script if the keyword source changes.
    println!("cargo:rerun-if-changed={}", toml_path.display());

    let content = fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("build.rs: cannot read {}: {e}", toml_path.display()));

    let value: toml::Value = content
        .parse()
        .expect("build.rs: invalid TOML in nlp_keywords.toml");

    let mut code = String::from(
        "// Auto-generated by build.rs from config/nlp_keywords.toml — DO NOT EDIT\n\n",
    );

    // ── IMPACT_KEYWORD_DATA ──────────────────────────────────────────
    code.push_str("static IMPACT_KEYWORD_DATA: &[(&str, &[&str])] = &[\n");
    let impact_order = [
        "people_impact",
        "housing_lc_impact",
        "infrastructure_impact",
        "services_impact",
        "systems_impact",
    ];
    if let Some(impact_table) = value.get("impact").and_then(|v| v.as_table()) {
        for label in &impact_order {
            if let Some(arr) = impact_table.get(*label).and_then(|v| v.as_array()) {
                let kw_list: Vec<String> = arr
                    .iter()
                    .filter_map(|v| v.as_str())
                    .map(|s| format!("\"{}\"", s))
                    .collect();
                code.push_str(&format!("    (\"{label}\", &[{}]),\n", kw_list.join(", ")));
            }
        }
    }
    code.push_str("];\n\n");

    // ── NEED_KEYWORD_DATA ────────────────────────────────────────────
    code.push_str("static NEED_KEYWORD_DATA: &[(&str, &[&str])] = &[\n");
    let need_order = [
        "food_security",
        "health",
        "wash",
        "protection",
        "education",
        "shelter",
        "logistics",
    ];
    if let Some(need_table) = value.get("need").and_then(|v| v.as_table()) {
        for label in &need_order {
            if let Some(arr) = need_table.get(*label).and_then(|v| v.as_array()) {
                let kw_list: Vec<String> = arr
                    .iter()
                    .filter_map(|v| v.as_str())
                    .map(|s| format!("\"{}\"", s))
                    .collect();
                code.push_str(&format!("    (\"{label}\", &[{}]),\n", kw_list.join(", ")));
            }
        }
    }
    code.push_str("];\n\n");

    // ── RISK_KEYWORD_DATA ────────────────────────────────────────────
    if let Some(risk_arr) = value
        .get("risk")
        .and_then(|v| v.get("keywords"))
        .and_then(|v| v.as_array())
    {
        let kw_list: Vec<String> = risk_arr
            .iter()
            .filter_map(|v| v.as_str())
            .map(|s| format!("\"{}\"", s))
            .collect();
        code.push_str(&format!(
            "static RISK_KEYWORD_DATA: &[&str] = &[{}];\n",
            kw_list.join(", ")
        ));
    }

    // Write to OUT_DIR
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("keywords.rs");
    fs::write(&dest, code).expect("build.rs: failed to write keywords.rs");
}
